plugins:
  ai_chat_translation_enabled:
    default: false
    client: true
  ai_chat_translation_backfill_hourly_rate:
    default: 0
    min: 0
    max: 100000
    client: false
  ai_chat_translation_backfill_max_age_days:
    default: 0
    min: 0
    max: 20000
    client: false
  ai_chat_translation_allowed_channel_ids:
    default: ""
    type: list
    list_type: ai_chat_translation_channel
    client: false
  ai_chat_translation_allowed_direct_message_channel_ids:
    default: ""
    type: list
    list_type: ai_chat_translation_direct_message_channel
    client: false
